blueprints/student.py
from curses import flash
from flask import Blueprint, abort, redirect, render_template, request, session
import services.courses as course_service
import services.free_form_tasks as free_form_task_service
import services.multiple_choice_tasks as multiple_choice_task_service
import services.statistics as statistics_service

student = Blueprint("student", __name__)


@student.route('/course_page', methods=['GET'])
def course_page():
    if "username" not in session:
        flash("Kirjaudu sisään niin voit tarkastella kurssisivua", "error")
        return redirect("/")

    if session.get("is_teacher"):
        flash("Opettajat eivät voi tarkastella opiskelijoiden kurssisivuja", "error")
        return redirect("/")

    course_id = request.args.get('course_id')
    user_id = session.get('user_id')
    course = course_service.get(course_id)
    materials = course_service.get_materials(course_id)
    free_form_tasks = free_form_task_service.get(course_id)
    free_form_submissions = free_form_task_service.get_submissions(user_id, course_id)
    multiple_choice_tasks = multiple_choice_task_service.get_without_answers(course_id)
    multiple_choice_submissions = multiple_choice_task_service.get_submissions(user_id, course_id)
    statistics = statistics_service.get_course_statistics_by_user_id(user_id, course_id)
    return render_template(
        'student/course_page.html',
        course=course,
        materials=materials,
        free_form_tasks=free_form_tasks,
        free_form_submissions=free_form_submissions,
        multiple_choice_tasks=multiple_choice_tasks,
        multiple_choice_submissions=multiple_choice_submissions,
        statistics=statistics)


@student.route('/add_new_multiple_choice_task_submission', methods=['POST'])
def add_new_multiple_choice_task_submission():
    if "username" not in session:
        flash('Kirjaudu sisään vastataksesi tehtäviin', 'error')
        return redirect("/")

    if session.get('is_teacher'):
        flash('Opettajat eivät voi vastata opiskelijoiden tehtäviin', 'error')
        return redirect("/")
    
    if session["csrf_token"] != request.form["csrf_token"]:
        abort(403)

    course_id = request.form['course_id']
    task_id = request.form['task_id']
    student_user_id = session['user_id']
    submission = multiple_choice_task_service.parse_submission(request)
    multiple_choice_task_service.create_submission(student_user_id, task_id, submission)
    return redirect(f'/course_page?course_id={course_id}')


@student.route('/add_new_free_form_task_submission', methods=['POST'])
def add_new_free_form_task_submission():
    if "username" not in session:
        flash('Kirjaudu sisään vastataksesi tehtäviin', 'error')
        return redirect("/")

    if session.get('is_teacher'):
        flash('Opettajat eivät voi vastata opiskelijoiden tehtäviin', 'error')
        return redirect("/")
    
    if session["csrf_token"] != request.form["csrf_token"]:
        abort(403)

    course_id = request.form['course_id']
    task_id = request.form['task_id']
    answer = request.form['answer']
    student_user_id = session.get('user_id')

    if not answer:
        flash("Vastaus puuttuu", "error")
        return redirect(f'/course_page?course_id={course_id}')

    free_form_task_service.create_submission(student_user_id, task_id, answer)
    return redirect(f'/course_page?course_id={course_id}')

templates/student/course_page.html
{% extends "base.html" %} 

{% block content %} 

<p>Olet kirjautunut opiskelijana nimellä {{ session.username }}</p>
<div style="display: flex; justify-content: space-between; align-items: center;">
    <a href="/logout">Kirjaudu ulos</a>
    <a href="/">Takaisin kaikkien kurssien näkymään</a>
</div>
<hr>
<div class="container-fluid">
    <h2>Katselet kurssia "{{ course.title }}"</h2>
    <br>
    <div class="row">
        <div class="col-md-6">
            <h2>Kurssin tekstimateriaali</h2>
            <div>
                {{ materials }}
            </div>
            <br>
            <h2>Tilastot</h2>
            <div>
                {{ statistics|length }} / {{ multiple_choice_tasks|length + free_form_tasks|length }} tehtävää tehty
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <h2>Kurssin monivalintatehtävät</h2>
                {% if multiple_choice_tasks|length == 0 %}
                <p>Kurssilla ei ole monivalintatehtäviä.</p>
                {% else %}
                <ul class="list-group">
                    {% for multiple_choice_task in multiple_choice_tasks %}
                    <li class="list-group-item">
                        <div>Kysymys: {{ multiple_choice_task.question }}</div>
                        <form action="add_new_multiple_choice_task_submission" method="POST">
                            <ul>
                                {% for option in multiple_choice_task.options %}
                                <li>
                                    {{ option.text }}
                                    <input type="hidden" name="all_options[{{ option.id }}]" value="{{ option.id }}">
                                    <input type="checkbox" name="selected_options[{{ option.id }}]" value="{{ option.id }}">
                                </li>
                                {% endfor %}
                            </ul>
                            <button type="submit" class="btn btn-primary">Lähetä vastaus</button>
                            <input type="hidden" name="course_id" value="{{ course.id }}">
                            <input type="hidden" name="task_id" value="{{ multiple_choice_task.id }}">
                            <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                        </form>
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <br>
            <div>
                <h2>Kurssin vapaamuotoiset tehtävät</h2>
                {% if free_form_tasks|length == 0 %}
                <p>Kurssilla ei ole vapaamuotoisia tehtäviä.</p>
                {% else %}
                <ul class="list-group">
                    {% for free_form_task in free_form_tasks %}
                    <li class="list-group-item">
                        <div>Kysymys: {{ free_form_task.question }}</div>
                        <div>Vastaukseni:</div>
                        <form action="/add_new_free_form_task_submission" method="post">
                            <input type="hidden" name="task_id" value="{{ free_form_task.id }}">
                            <input type="hidden" name="course_id" value="{{ course.id }}">
                            <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                            <textarea class="form-control" id="answer" name="answer" rows="5" required></textarea>
                            <br>
                            <button type="submit" class="btn btn-primary">Lähetä vastaus</button>
                        </form>
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <br>
            <div>
                <h2>Lähettämäni vastaukset</h2>
                <br>
                <div>
                    <h4>Vapaamuotoiset tehtävät</h4>
                    {% if free_form_submissions|length == 0 %}
                    <p>En ole lähettänyt vapaamuotoisia tehtäviä.</p>
                    {% else %}
                    <br>
                    <ul class="list-group">
                        {% for free_form_submission in free_form_submissions %}
                        <li class="list-group-item">
                            <div>Kysymys: {{ free_form_submission.question }}</div>
                            <br>
                            <div>Vastaukseni: {{ free_form_submission.answer }}</div>
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                <br>
                <div>
                    <h4>Monivalintatehtävät</h4>
                    {% if multiple_choice_submissions|length == 0 %}
                    <p>En ole lähettänyt monivalintatehtäviä.</p>
                    {% else %}
                    <ul class="list-group">
                        {% for multiple_choice_submission in multiple_choice_submissions %}
                        <br>
                        <li class="list-group-item">
                            <div>Kysymys: {{ multiple_choice_submission.question }}
                            </div>
                            <br>
                            {% for option in multiple_choice_submission.options %}
                            <div>{{ option.text }} - {% if option.students_choice %}oikein{% else %}väärin{% endif %}
                            </div>
                            {% endfor %}
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/student/dashboard.html
{% extends "base.html" %} 

{% block content %} 

<p>Olet kirjautunut opiskelijana nimellä {{ session.username }}</p>
<a href="/logout">Kirjaudu ulos</a>
<hr>
<div class="container-fluid">
  <div class="row">
      <div class="col-md-6">
          <h2>Sinun kurssit</h2>
          <ul class="list-group">
              {% for course in joined_courses %}
              <li class="list-group-item">
                <a href="{{ url_for('student.course_page', course_id=course.id) }}">{{ course.title }}</a>
              </li>
              {% else %}
              <li class="list-group-item">Sinulla ei ole kursseja.</li>
              {% endfor %}
          </ul>
      </div>
      <div class="col-md-6">
          <h2>Liity kurssille</h2>
          <ul class="list-group">
            {% for course in available_courses %}
            <li class="list-group-item">
              <form action="join_course" method="POST">
                <input type="hidden" name="course_id" value="{{ course.id }}">
                <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                <button type="submit" class="btn btn-link">{{course.title}}</button>
              </form>
            </li>
            {% else %}
            <li class="list-group-item">Kursseja ei ole.</li>
            {% endfor %}
        </ul>
      </div>
  </div>
</div>

{% endblock %}