blueprints/teacher.py
from flask import Blueprint, abort, flash, redirect, render_template, request, session
import services.courses as course_service
import services.multiple_choice_tasks as multiple_choice_task_service
import services.free_form_tasks as free_form_task_service
import services.statistics as statistics_service

teacher = Blueprint("teacher", __name__)


@teacher.route('/edit_course', methods=['GET'])
def edit_course():
    if not session.get('is_teacher'):
        flash('Vain opettajat voivat muokata kursseja', 'error')
        return redirect('/')

    course_id = request.args.get('course_id')
    option_count = request.args.get('option_count', default=4, type=int)
    course = course_service.get(course_id)
    materials = course_service.get_materials(course_id)
    students = statistics_service.get_students_with_submissions(course_id)
    multiple_choice_tasks = multiple_choice_task_service.get(course_id)
    free_form_tasks = free_form_task_service.get(course_id)
    course_statistics = statistics_service.get_course_statistics(course_id)
    return render_template(
        'teacher/edit_course.html',
        course=course,
        materials=materials,
        students=students,
        option_count=option_count,
        multiple_choice_tasks=multiple_choice_tasks,
        free_form_tasks=free_form_tasks,
        course_statistics=course_statistics)


@teacher.route('/create_course', methods=['POST'])
def create_course():
    if not session.get('username'):
        flash('Vain kirjautuneet käyttäjät voivat luoda kursseja', 'error')
        return redirect('/')

    if not session.get('is_teacher'):
        flash('Vain opettajat voivat luoda kursseja', 'error')
        return redirect('/')
    
    if session["csrf_token"] != request.form["csrf_token"]:
        abort(403)

    title = request.form['title']
    description = request.form['description']

    if not course_service.is_valid_course(title, description):
        flash('Kurssin tiedot eivät kelpaa', 'error')
        return redirect('/')

    course_service.create(session.get('user_id'), title, description)
    flash('Kurssin luonti onnistui', 'success')
    return redirect('/')


@teacher.route('/update_course_materials', methods=['POST'])
def update_course_materials():
    if not session.get('username'):
        flash('Vain kirjautuneet käyttäjät voivat muokata kursseja', 'error')
        return redirect('/')

    if not session.get('is_teacher'):
        flash('Vain opettajat voivat muokata kursseja', 'error')
        return redirect('/')
    
    if session["csrf_token"] != request.form["csrf_token"]:
        abort(403)

    course_id = request.form['course_id']
    materials = request.form['materials']

    course_service.update_materials(course_id, materials)
    flash('Kurssimateriaali päivitetty onnistuneesti.', 'success')
    return redirect(f'/edit_course?course_id={course_id}')


@teacher.route('/delete_course', methods=['POST'])
def delete_course():
    if not session.get('username'):
        flash('Vain kirjautuneet käyttäjät voivat poistaa kursseja', 'error')
        return redirect('/')

    if not session.get('is_teacher'):
        flash('Vain opettajat voivat poistaa kursseja', 'error')
        return redirect('/')
    
    if session["csrf_token"] != request.form["csrf_token"]:
        abort(403)

    course_id = request.form['course_id']
    course_service.delete(course_id)
    return redirect('/')


@teacher.route('/update_course_title', methods=['POST'])
def update_course_title():
    if not session.get('username'):
        flash('Vain kirjautuneet käyttäjät voivat muokata kursseja', 'error')
        return redirect('/')

    if not session.get('is_teacher'):
        flash('Vain opettajat voivat muokata kursseja', 'error')
        return redirect('/')
    
    if session["csrf_token"] != request.form["csrf_token"]:
        abort(403)

    course_id = request.form['course_id']
    new_title = request.form['new_title']
    was_update_successful = course_service.update_title(course_id, new_title)

    if was_update_successful:
        flash('Kurssin nimi päivitettiin onnistuneesti', 'success')
        return redirect(f'/edit_course?course_id={course_id}')
    else:
        flash(
            'Kurssin nimen päivitys epäonnistui. Nimen tulee olla määritelty ja se saa olla enintään 255 merkkiä pitkä.',
            'error')
        return redirect(f'/edit_course?course_id={course_id}')
    

@teacher.route('/add_new_multiple_choice_task', methods=['POST'])
def add_new_multiple_choice_task():
    if not session.get('username'):
        flash('Vain kirjautuneet käyttäjät voivat lisätä tehtäviä', 'error')
        return redirect('/')
    
    if not session.get('is_teacher'):
        flash('Vain opettajat voivat lisätä tehtäviä', 'error')
        return redirect('/')
    
    if session["csrf_token"] != request.form["csrf_token"]:
        abort(403)

    course_id = request.form['course_id']
    question = request.form['question']

    if not question:
        flash("Kysymys puuttuu", "error")
        return redirect(f'/edit_course?course_id={course_id}')

    option_count = request.form['option_count']
    options = multiple_choice_task_service.parse_options(request)
    multiple_choice_task_service.create_task(course_id, question, options)
    return redirect(
        f'/edit_course?course_id={course_id}&option_count={option_count}')

@teacher.route('/add_new_free_form_task', methods=['POST'])
def add_new_free_form_task():
    if not session.get('username'):
        flash('Vain kirjautuneet käyttäjät voivat lisätä tehtäviä', 'error')
        return redirect('/')

    if not session.get('is_teacher'):
        flash('Vain opettajat voivat lisätä tehtäviä', 'error')
        return redirect('/')
    
    if session["csrf_token"] != request.form["csrf_token"]:
        abort(403)

    course_id = request.form['course_id']
    question = request.form['question']
    evaluation_criteria = request.form['evaluation_criteria']
    option_count = request.form['option_count']
    free_form_task_service.create_task(course_id, question, evaluation_criteria)
    return redirect(
        f'/edit_course?course_id={course_id}&option_count={option_count}')


@teacher.route('/view_student_submissions', methods=['POST'])
def view_student_submissions():
    if not session.get("username"):
        flash("Vain kirjautuneet käyttäjät voivat lisätä tehtäviä", "error")
        return redirect("/")

    if not session.get("is_teacher"):
        flash("Vain opettajat voivat lisätä tehtäviä", "error")
        return redirect("/")
    
    if session["csrf_token"] != request.form["csrf_token"]:
        abort(403)

    course_id = request.form["course_id"]
    student_id = request.form["student_id"]
    student_username = request.form["student_username"]
    free_form_submissions = free_form_task_service.get_submissions(student_id, course_id)
    multiple_choice_submissions = multiple_choice_task_service.get_submissions(student_id, course_id)

    for submission in multiple_choice_submissions:
        submission["is_correct"] = multiple_choice_task_service.is_correct(submission["submission_id"])

    return render_template(
        "teacher/student_submissions.html",
        course_id=course_id,
        student_id=student_id,
        student_username=student_username,
        free_form_submissions=free_form_submissions,
        multiple_choice_submissions=multiple_choice_submissions,)

templates/teacher/dashboard.html
{% extends "base.html" %} 

{% block content %} 

<p>Olet kirjautunut opettajana nimellä {{ session.username }}</p>
<a href="/logout">Kirjaudu ulos</a>
<hr>
<div class="container-fluid">
  <div class="row">
      <div class="col-md-6">
          <h2>Sinun kurssit</h2>
          <ul class="list-group">
              {% for course in courses %}
                <li class="list-group-item">
                    <a href="{{ url_for('teacher.edit_course', course_id=course.id) }}">{{ course.title }}</a>
                </li>
              {% else %}
              <li class="list-group-item">Sinulla ei ole kursseja.</li>
              {% endfor %}
          </ul>
      </div>
      <div class="col-md-6">
          <h2>Luo uusi kurssi</h2>
          <form action="/create_course" method="post">
              <div class="form-group">
                  <label for="title">Kurssin nimi</label>
                  <input type="text" class="form-control" id="title" name="title" required>
              </div>
              <div class="form-group">
                  <label for="description">Kurssin kuvaus</label>
                  <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Luo kurssi</button>
              <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
          </form>
      </div>
  </div>
</div>

{% endblock %}

templates/teacher/edit_course.html
{% extends "base.html" %} 

{% block content %} 

<p>Olet kirjautunut opettajana nimellä {{ session.username }}</p>
<div style="display: flex; justify-content: space-between; align-items: center;">
    <a href="/logout">Kirjaudu ulos</a>
    <a href="/">Takaisin kaikkien kurssien näkymään</a>
</div>
<hr>
<div class="container-fluid">
<h2>Muokkaat kurssia "{{ course.title }}"</h2>
<br>
  <div class="row">
    <div class="col-md-6">
        <div>
            <h2>Kurssin kuvaus</h2>
            <div>{{ course.description }}</div>
            <br>
            <h2>Kurssin tekstimateriaali</h2>
            <form action="/update_course_materials" method="POST">
                <input type="hidden" name="course_id" value="{{ course.id }}">
                <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                <div class="form-group">
                    <textarea class="form-control" id="materials" name="materials" rows="5" required>{{ materials }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Päivitä tekstimateriaali</button>
            </form>
        </div>
        <br>
        <div>
            <h2>Kurssin tilastotietoja</h2>
            <br>

            {% if students|length == 1 %}
            <p>Kurssilla on {{ students|length }} opiskelija.</p>
            {% else %}
            <p>Kurssilla on {{ students|length }} opiskelijaa.</p>
            {% endif %}

            {% if students|length > 0 %}
            <p>Kurssin tilastotietoja:</p>
            <ul class="list-group">
                {% for student in students %}
                <li class="list-group-item">
                    <p>opiskelija {{ student.username }}</p>
                    <p>vastannut {{ student.submissions|length }} / {{ multiple_choice_tasks|length + free_form_tasks|length }} tehtävään</p>
                    <form action="/view_student_submissions", method="POST">
                        <input type="hidden" name="course_id" value="{{ course.id }}">
                        <input type="hidden" name="student_id" value="{{ student.id }}">
                        <input type="hidden" name="student_username" value="{{ student.username }}">
                        <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                        <button type="submit" class="btn btn-primary">Katsele vastauksia</button>
                    </form>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
        <div class="col-md-6">
            <h2>Lisää uusi monivalintatehtävä</h2>
            <p>Vastausvaihtoehtojen määrä</p>
            <form action="" method="GET">
                <input type="hidden" name="course_id" value="{{ course.id }}">
                <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                <div>
                    <input type="number" id="new_option_count" name="option_count" min="2" max="30" value="{{ option_count }}">
                </div>
                <br>
                <div>
                    <button type="submit" class="btn btn-primary">Muuta vastausvaihtoehtojen määrää</button>
                </div>
            </form>
            <br>
            <form action="/add_new_multiple_choice_task" method="POST">
                <p>Tehtävän kysymys:</p>
                <input type="hidden" name="course_id" value="{{ course.id }}">
                <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                <div class="form-group">
                    <textarea class="form-control" id="question" name="question" rows="3" required></textarea>
                </div>
                <p>Tehtävän vastausvaihtoehdot:</p>
                <div class="form-group">
                    {% for i in range(option_count) %}
                    <div style="display: flex; align-items: center">
                        <input type="text" class="form-control" id="option{{ i+1 }}" name="options[{{ i }}][text]"placeholder="Vaihtoehto {{ i+1 }}" required>
                        <input type="checkbox" id="correct{{ i+1 }}" name="options[{{ i }}][is_correct]">
                        <label for="correct{{ i+1 }}">Oikein</label>
                    </div>
                    {% endfor %}
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Lisää monivalintatehtävä</button>
                <br>
                <input type="hidden" name="option_count" value="{{ option_count }}">
            </form>
            <br>
            <h2>Lisää uusi vapaamuotoinen tehtävä</h2>
            <form action="/add_new_free_form_task" method="POST">
                <p>Tehtävän kysymys:</p>
                <input type="hidden" name="course_id" value="{{ course.id }}">
                <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                <div class="form-group">
                    <textarea class="form-control" id="question" name="question" rows="3" required></textarea>
                </div>
                <p>Tehtävän arviointikriteerit:</p>
                <div class="form-group">
                    <textarea class="form-control" id="evaluation-criteria" name="evaluation_criteria" rows="5" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Lisää tehtävä</button>
                <input type="hidden" name="option_count" value="{{ option_count }}">
            </form>
            <br>
            <div>
                <h2>Kurssin monivalintatehtävät</h2>
                <ul class="list-group">
                    {% for multiple_choice_task in multiple_choice_tasks %}
                    <li class="list-group-item">
                        <div>Kysymys: {{ multiple_choice_task.question }}</div>
                        <div>Vastausvaihtoehdot:
                            <ul>
                                {% for option in multiple_choice_task.options %}
                                <li>{{ option.text }} - {{ 'oikein' if option.is_correct else 'väärin' }}</li>
                                {% else %}
                                <p>Ei vastausvaihtoehtoja.</p>
                                {% endfor %}
                            </ul>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <br>
            <div>
                <h2>Kurssin vapaamuotoiset tehtävät</h2>
                <ul class="list-group">
                    {% for free_form_task in free_form_tasks %}
                    <li class="list-group-item">
                        <div>Kysymys: {{ free_form_task.question }}</div>
                        <div>Arviointikriteerit: {{ free_form_task.evaluation_criteria }}</div>
                    </li>
                    {% endfor %}
            </div>
            <br>
            <div>
                <h2>Muokkaa kurssia</h2>
                <form action="/update_course_title" method="POST">
                    <input type="hidden" name="course_id" value="{{ course.id }}">
                    <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                    <div class="form-group">
                        <label for="title">Kurssin uusi nimi</label>
                        <input type="text" class="form-control" id="new_title" name="new_title">
                    </div>
                    <button type="submit" class="btn btn-primary">Päivitä kurssin nimi</button>
                </form>
            </div>
            <br>
            <div>
                <h2>Poista kurssi</h2>
                <form action="/delete_course" method="POST">
                    <input type="hidden" name="course_id" value="{{ course.id }}">
                    <input type="hidden" name="csrf_token" value="{{ session.csrf_token }}">
                    <button type="submit" class="btn btn-danger">Poista kurssi</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/teacher/student_submissions.html
{% extends "base.html" %} 

{% block content %}

<p>Olet kirjautunut opettajana nimellä {{ session.username }}</p>
<div style="display: flex; justify-content: space-between; align-items: center;">
    <a href="/logout">Kirjaudu ulos</a>
    <a href="/edit_course?course_id={{course_id}}">Takaisin kurssisivulle</a>
    <a href="/">Takaisin kaikkien kurssien näkymään</a>
</div>
<hr>
<div class="container-fluid">
  <h2>Katselet opiskelijan {{ student_username }} tehtävävastauksia</h2>
  <br>
  <div class="row">
    <div class="col-md-6">
      <div>
        <h3>Vapaamuotoiset tehtävät</h3>
        {% if free_form_submissions|length == 0 %}
        <p>Opiskelija ei ole tehnyt vapaamuotoisia tehtäviä.</p>
        {% else %}
        <ul class="list-group">
          {% for free_form_submission in free_form_submissions %}
          <li class="list-group-item">
            <p>Tehtävän id: {{ free_form_submission.task_id }}</p>
            <p>Vastausaika: {{ free_form_submission.submission_time }}</p>
            <p>Kysymys: {{ free_form_submission.question }}</p>
            <p>Vastaus: {{ free_form_submission.answer }}</p>
          </li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>
      <h3>Monivalintatehtävät</h3>
      {% if multiple_choice_submissions|length == 0 %}
      <p>Opiskelija ei ole tehnyt monivalintatehtäviä.</p>
      {% else %}
      <ul class="list-group">
        {% for multiple_choice_submission in multiple_choice_submissions %}
        <li class="list-group-item">
          <p>Tehtävän id: {{ multiple_choice_submission.task_id }}</p>
          <p>Vastausaika: {{ multiple_choice_submission.submission_time }}</p>
          <p>Kysymys: {{ multiple_choice_submission.question }}</p>
          <p>Vastaus:</p>
          {% for option in multiple_choice_submission.options %}
          <div>{{ option.text }} - {% if option.students_choice %}oikein{% else %}väärin{% endif %}
          </div>
          {% endfor %}
          <br>
          {% if multiple_choice_submission.is_correct %}
          <p>Vastaus on oikein.</p>
          {% else %}
          <p>Vastaus on väärin.</p>
          {% endif %}
        </li>
        {% endfor %}
      </ul>
      {% endif %}
</div>

{% endblock %}